use soroban_sdk::contracterror;

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum RoundChainError {
    CircleNotFound = 1,
    MemberNotFound = 2,
    CircleFull = 3,
    CircleNotPending = 4,
    CircleNotActive = 5,
    CircleNotCompleted = 6,
    NotCreator = 7,
    AlreadyMember = 8,
    NotEnoughMembers = 9,
    AlreadyContributed = 10,
    MemberSlashed = 11,
    PayoutTooEarly = 12,
    CannotSlash = 13,
    AlreadySlashed = 14,
    CollateralAlreadyClaimed = 15,
    InvalidAmount = 16,
    InvalidMaxMembers = 17,
    InvalidPeriod = 18,
    AlreadyReceivedPayout = 19,
    InsufficientTrustScore = 20,
    NotAllContributed = 21,
    RecipientNotPaid = 22,
    CircleCancelled = 23,
    JoinDeadlinePassed = 24,
    NotMember = 25,
    CannotCancel = 26,
    InvalidToken = 27,
    CannotExitEarly = 28,
    UseCompleteExit = 29,
    MemberExited = 30,
    AlreadyInitialized = 31,
    NotInitialized = 32,
    NoPayoutReceived = 33,
}
